services:
  - type: web
    name: logscale-backend
    runtime: node
    rootDir: apps/backend
    buildCommand: npm install --omit=dev && npx prisma generate
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_TLS
        value: true
